using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace CCOInsights.SubscriptionManager.Generators;

[Generator]
public class ProviderGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Defines a syntax provider that picks up only decorated type declarations
        var declarations = context.SyntaxProvider
            .CreateSyntaxProvider(
                static (node, _) =>
                    node is TypeDeclarationSyntax tds &&
                    tds.AttributeLists.Any(al => al.ToString().StartsWith("[GeneratedProvider")),
                static (syntaxContext, _) => (TypeDeclarationSyntax)syntaxContext.Node
            )
            .Where(static decl => decl is not null);

        // Registers an output action to generate the code
        context.RegisterSourceOutput(declarations, (spc, declaration) =>
        {
            var autoGeneratedDeclaration = declaration!;

            // Existing logic moved here
            var namespaceName = autoGeneratedDeclaration.Parent?.GetType()!
                .GetProperty("Name")!
                .GetValue(autoGeneratedDeclaration.Parent)?.ToString() ?? "UnknownNamespace";

            var className = autoGeneratedDeclaration.Identifier
                .ToString().Replace("Response", "");

            var paramsToInject = TemplateParameters.Create(
                namespaceName,
                className,
                autoGeneratedDeclaration.Identifier.ToString(),
                autoGeneratedDeclaration.AttributeLists[0]
                    .Attributes[0].ArgumentList!.Arguments[0]
                    .ToString()
            );

            var template = getSourceCode();
            var sourceGenerated = replaceParametersInTemplate(template, paramsToInject);

            spc.AddSource($"ProviderGenerated_{paramsToInject.GeneratedClassName}.g.cs",
                SourceText.From(sourceGenerated, Encoding.UTF8));
        });
    }

    private string replaceParametersInTemplate(string template, TemplateParameters parameters)
    {
        return template
            .Replace("{{" + nameof(parameters.GeneratedNamespace) + "}}", parameters.GeneratedNamespace)
            .Replace("{{" + nameof(parameters.GeneratedClassName) + "}}", parameters.GeneratedClassName)
            .Replace("{{" + nameof(parameters.GeneratedResponseName) + "}}", parameters.GeneratedResponseName)
            .Replace("{{" + nameof(parameters.Path) + "}}", parameters.Path);
    }

    private string getSourceCode()
    {
        string path = "CCOInsights.SubscriptionManager.Generators.Templates.CodeGenerated.txt";
        using var stream = GetType().Assembly.GetManifestResourceStream(path);
        using var sr = new StreamReader(stream!);
        return sr.ReadToEnd();
    }
}
