# CCO Dashboard Builds

pr: none

phases:
- phase: build_CCOD
  displayName: Build CCO Dashboard
  queue:
    name: Hosted VS2017

  steps:

  - task: CopyFiles@2
    inputs:
      Contents: |
            dashboards\**
            docs\**
            install\**
            queries\**
            README.md
            LICENSE
            !.github\**
            !.git\**\*
      TargetFolder: '$(Build.artifactstagingdirectory)'
      CleanTargetFolder: true

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(build.artifactstagingdirectory)'
      ArtifactName: 'ccodashboard'
      ArtifactType: 'Container'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(build.artifactstagingdirectory)/dashboards/CCODashboard-AKS'
      ArtifactName: 'ccodashboard-release-AKS'
      ArtifactType: 'Container'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(build.artifactstagingdirectory)/dashboards/CCODashboard'
      ArtifactName: 'ccodashboard-release'
      ArtifactType: 'Container'
