name: "GitHub Contributions"

on:
  workflow_dispatch:
    inputs:
      resourceGroupName:
        type: string
        description: "Resource Group where infrastructure will be deployed/updated"
        required: true
        default: ""

jobs:
  deploy_dashboard:
    runs-on: windows-2022
    name: "Dashboard Backend"
    steps:
      - name: "Checkout"
        uses: actions/checkout@0717577d45739eb3c851188b29f50ed6c0b2194e # v2.8.0
        with:
          fetch-depth: 0
      - name: Azure Login
        uses: Azure/login@cb79c773a3cfa27f31f25eb3f677781210c9ce3d # v1.6.1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: true
      - name: "Deploy infrastructure"
        id: rg
        uses: azure/arm-deploy@65ae74fb7aec7c680c88ef456811f353adae4d06 # v1.0.9
        with:
          deploymentName: ${{ github.event.inputs.resourceGroupName }}
          resourceGroupName: ${{ github.event.inputs.resourceGroupName }}
          template: ./dashboards/GitHubDashboard-Contributors/infrastructure/deploy.bicep
      - name: "Replace tokens"
        shell: pwsh
        run: |
          $ConvertTokenListFunctionInput = @{
            FilePath   = './dashboards/GitHubDashboard-Contributors/src/local.settings.json'
            TokenName  = '<<PAT>>'
            TokenValue = '${{ secrets.PAT }}'
          }
          ./tools/scripts/Convert-TokenInFile.ps1 @ConvertTokenListFunctionInput -Verbose
      - name: "Deploy code"
        shell: pwsh
        run: |
          # Initialize parameters
          Install-Module -Name Az.Functions -Force
          $functionApp = Get-AzFunctionApp -ResourceGroupName '${{ github.event.inputs.resourceGroupName }}'
          $functionAppName = $functionApp[0].Name
          $DeployFunctionInputs = @{
              ResourceGroup      = '${{ github.event.inputs.resourceGroupName }}'
              FunctionAppName    = $functionAppName
              Dashboard          = 'GitHub'
          }
          # Invoke Function
          ./tools/scripts/deploy-function.ps1 @DeployFunctionInputs -Verbose
