name: Sync issue to Azure DevOps work item

on:
  issues:
    types:
      [opened]

jobs:
  alert:
    runs-on: ubuntu-latest
    steps:
      - uses: danhellem/github-actions-issue-to-work-item@master
        env:
          ado_token: "${{ secrets.ADOPAT }}"
          github_token: "${{ secrets.PAT }}"
          ado_organization: "strategy-and-solutions"
          ado_project: "product-portfolio"
          ado_area_path: "product-portfolio\\CCO Insights"
          ado_wit: "User Story"
          ado_new_state: "New"
          ado_active_state: "Active"
          ado_close_state: "Closed"
          ado_bypassrules: true
          log_level: 100
