name: "Release"

on: # yamllint disable-line rule:truthy
  push:
    branches: [master]
    paths:
      - "ccodashboard/dashboards/*"
      - ".github/workflows/release.yml"

jobs:
  release:
    name: "Release"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Determine tag"
        run: "echo \"RELEASE_TAG=${GITHUB_REPOSITORY}.v$GITHUB_RUN_NUMBER\" >> $GITHUB_ENV"
      - name: "Create release"
        uses: "actions/github-script@v5"
        with:
          github-token: "${{ secrets.PAT }}"
          script: |
            try {
              await github.rest.repos.createRelease({
                draft: false,
                generate_release_notes: true,
                name: process.env.RELEASE_TAG,
                owner: context.repo.owner,
                prerelease: false,
                repo: context.repo.repo,
                tag_name: process.env.RELEASE_TAG,
              });
            } catch (error) {
              core.setFailed(error.message);
            }
